## What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [68]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [69]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [70]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---

   **Data types in arrays**

- You can set the data types for these arrays. NumPy has built in datatypes with variable sizes.
- For example, you can use int64, int32, int16, etc for integers. Default size differs from software to software.
- You can access them using np.int64 syntax.

---

In [71]:
# dtype

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [72]:
# np.arange - works same as range() function in python. Takes in start, end and step size.

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [73]:
# with reshape - You give the dimensions for the array / matrix

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [74]:
# np.ones and np.zeros - as you guessed, initializes arrays with ones or zeros. You just give the dimensions.

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
# np.random - values between 0 and 100, so that you can scale them however you like.
# You call random twice because numpy has class ramdom which has function random() in it.

np.random.random((3,4))

array([[0.92884194, 0.76065299, 0.97041786, 0.35774116],
       [0.43090665, 0.02361007, 0.38137595, 0.34477822],
       [0.69367628, 0.90342168, 0.33683135, 0.27455848]])

In [77]:
# np.linspace - creates evenly arithmatically distributed values for arrays. 
#Takes in start, end and no. of elements to be created.

np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [78]:
# np.identity - creates identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [79]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [80]:
# ndim - returns number of dimensions of the array.

a3.ndim

3

In [81]:
# shape - returns tuple of shape of array.

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
# size - number of elements in the array

print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [83]:
# itemsize
a3.itemsize

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int32


### Changing Datatype

In [85]:
# astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [86]:
# reshape

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [88]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [89]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

### Array Functions

In [90]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[74., 58., 49.],
       [58., 28., 33.],
       [43., 26., 98.]])

In [91]:
# max/min/sum/prod
# 0 -> col and 1 -> row

np.prod(a1,axis=0)

array([184556.,  42224., 158466.])

In [92]:
# mean/median/std/var
np.var(a1,axis=1)

array([106.88888889, 172.22222222, 944.22222222])

In [93]:
# trigonomoetric functions
np.sin(a1)

array([[-0.98514626,  0.99287265, -0.95375265],
       [ 0.99287265,  0.27090579,  0.99991186],
       [-0.83177474,  0.76255845, -0.57338187]])

In [94]:
# dot product - Inner product. Columns of 1st matrix must be equal to rows of 2nd matrix
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [95]:
# log and exponents
np.exp(a1)

array([[1.37338298e+32, 1.54553894e+25, 1.90734657e+21],
       [1.54553894e+25, 1.44625706e+12, 2.14643580e+14],
       [4.72783947e+18, 1.95729609e+11, 3.63797095e+42]])

In [96]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[41., 83., 60.],
       [60., 53., 68.]])

### Indexing and Slicing

In [97]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[1,0]

4

In [101]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
a3[1,0,1]

5

In [103]:
a3[1,1,0]

6

In [104]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a1[2:5:2]

array([2, 4])

In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [108]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [109]:
a2[1,::3]

array([4, 7])

In [110]:
a2[0,:]

array([0, 1, 2, 3])

In [111]:
a2[:,2]

array([ 2,  6, 10])

In [112]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [115]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [116]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [137]:
a1

for i in a1:
  print(i, end = "\t")

0	1	2	3	4	5	6	7	8	9	

In [118]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [120]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
for i in a3[0,:,:]:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [122]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [136]:
for i in np.nditer(a3): # iterates over all elements the entire array.
  print(i, end = "\t")

0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	

### Reshaping

In [124]:
# reshape

In [125]:
# Transpose - You can use both methods mentioned below.

np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [126]:
# ravel - equivalent to reshaping into 1 dimension

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [127]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [128]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [129]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [130]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [132]:
# vertical splitting

In [133]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [149]:
arr1, arr2, arr3 = np.vsplit(a5,3)
print(arr1)

print()

arr = np.vsplit(a5,3)
print(type(arr))
print(arr)

[[12 13 14 15]]

<class 'list'>
[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
