### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[52, 74, 95, 75],
       [48, 44, 96, 23],
       [ 8, 96, 32, 98],
       [63, 14,  2, 78],
       [49, 58, 61,  5],
       [74, 38, 61, 43]])

In [4]:
np.sort(b, axis=1) # axis=1 sorted the row. 

array([[52, 74, 75, 95],
       [23, 44, 48, 96],
       [ 8, 32, 96, 98],
       [ 2, 14, 63, 78],
       [ 5, 49, 58, 61],
       [38, 43, 61, 74]])

In [5]:
# You can't directly reverse sort the arrays. You have to use array splicing.

np.sort(a)[::-1]

array([98, 89, 87, 87, 83, 72, 66, 65, 51, 47, 46, 42, 30, 13, 13])

In [6]:
np.sort(b,axis=0)

array([[ 8, 14,  2,  5],
       [48, 38, 32, 23],
       [49, 44, 61, 43],
       [52, 58, 61, 75],
       [63, 74, 95, 78],
       [74, 96, 96, 98]])

In [7]:
np.sort(b,axis=0)[::-1]

array([[74, 96, 96, 98],
       [63, 74, 95, 78],
       [52, 58, 61, 75],
       [49, 44, 61, 43],
       [48, 38, 32, 23],
       [ 8, 14,  2,  5]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
np.append(a,200)

array([ 89,  65,  42,  66,  51,  46,  47,  30,  87,  83,  13,  98,  72,
        87,  13, 200])

In [9]:
b

array([[52, 74, 95, 75],
       [48, 44, 96, 23],
       [ 8, 96, 32, 98],
       [63, 14,  2, 78],
       [49, 58, 61,  5],
       [74, 38, 61, 43]])

In [10]:
np.append(b,np.random.random((b.shape[0],1))*100,axis=1)

array([[52.        , 74.        , 95.        , 75.        , 12.5067084 ],
       [48.        , 44.        , 96.        , 23.        , 75.93745547],
       [ 8.        , 96.        , 32.        , 98.        , 37.51784383],
       [63.        , 14.        ,  2.        , 78.        , 88.45573114],
       [49.        , 58.        , 61.        ,  5.        , 53.90051326],
       [74.        , 38.        , 61.        , 43.        , 12.24648722]])

In [11]:
np.append(b, np.ones((b.shape[-2],1)), axis=1)

array([[52., 74., 95., 75.,  1.],
       [48., 44., 96., 23.,  1.],
       [ 8., 96., 32., 98.,  1.],
       [63., 14.,  2., 78.,  1.],
       [49., 58., 61.,  5.,  1.],
       [74., 38., 61., 43.,  1.]])

In [12]:
np.delete(b, [-1], axis=1)

array([[52, 74, 95],
       [48, 44, 96],
       [ 8, 96, 32],
       [63, 14,  2],
       [49, 58, 61],
       [74, 38, 61]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
# code
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [19]:
a.T

# Notice that a and a.T are the same, because it's a 1D vector.
# 1D vectors are by default row vectors.

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [20]:
np.expand_dims(a,axis=0)

array([[89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13]])

In [21]:
np.expand_dims(a,axis=0).shape
# This expanded the array from 1D to 2D
# axis=0 adds column, axis=1 adds row

(1, 15)

In [22]:
np.expand_dims(a,axis=1)

array([[89],
       [65],
       [42],
       [66],
       [51],
       [46],
       [47],
       [30],
       [87],
       [83],
       [13],
       [98],
       [72],
       [87],
       [13]])

In [23]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [24]:
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [25]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  8,  9, 11, 12, 13], dtype=int64),)

In [26]:
# replace all values > 50 with 0
# The 2nd optional argument takes in the value that we wanna replace with if condition is true.
# 3rd optional argument takes in value we wanna replace with if condition is false.

np.where(a>50,0,a)

array([ 0,  0, 42,  0,  0, 46, 47, 30,  0,  0, 13,  0,  0,  0, 13])

In [27]:
np.where(a%2 == 0,0,a)

array([89, 65,  0,  0, 51,  0, 47,  0, 87, 83, 13,  0,  0, 87, 13])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [28]:
# code
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [29]:
np.argmax(a)

11

In [30]:
b

array([[52, 74, 95, 75],
       [48, 44, 96, 23],
       [ 8, 96, 32, 98],
       [63, 14,  2, 78],
       [49, 58, 61,  5],
       [74, 38, 61, 43]])

In [31]:
np.argmax(b,axis=0)

array([5, 2, 1, 2], dtype=int64)

In [32]:
np.argmax(b,axis=1)

array([2, 2, 3, 3, 2, 0], dtype=int64)

In [33]:
# np.argmin
np.argmin(a)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [34]:
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [35]:
np.cumsum(a)

array([ 89, 154, 196, 262, 313, 359, 406, 436, 523, 606, 619, 717, 789,
       876, 889], dtype=int32)

In [36]:
b

array([[52, 74, 95, 75],
       [48, 44, 96, 23],
       [ 8, 96, 32, 98],
       [63, 14,  2, 78],
       [49, 58, 61,  5],
       [74, 38, 61, 43]])

In [37]:
np.cumsum(b,axis=1)

array([[ 52, 126, 221, 296],
       [ 48,  92, 188, 211],
       [  8, 104, 136, 234],
       [ 63,  77,  79, 157],
       [ 49, 107, 168, 173],
       [ 74, 112, 173, 216]], dtype=int32)

In [38]:
np.cumsum(b)

array([  52,  126,  221,  296,  344,  388,  484,  507,  515,  611,  643,
        741,  804,  818,  820,  898,  947, 1005, 1066, 1071, 1145, 1183,
       1244, 1287], dtype=int32)

In [39]:
# np.cumprod
np.cumprod(a)

array([         89,        5785,      242970,    16036020,   817837020,
       -1034202744, -1362888712,  2063011600,  -906617232,  2060181072,
        1012550160,   445667872,  2023315712,   -65192192,  -847498496],
      dtype=int32)

In [40]:
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [41]:
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [42]:
np.percentile(a,99) # It even interpolates the data to find random percentiles like this.

96.74

In [43]:
print(np.percentile(a,100)) # 100 percentile is the max elememt.
print()
print(np.percentile(a,0)) # 0 percentile is the min element.

98.0

13.0


In [44]:
print(np.percentile(a,95))

91.69999999999999


In [45]:
np.percentile(a,50)

65.0

In [46]:
np.median(a) # median is the 50th percentile

65.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
# code
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [48]:
np.histogram(a,bins=[0,50,100]) # frequency count for no. of elements in a bin

(array([6, 9], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [50]:
# code
a


array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [51]:
# It basically finds intersection of two arrays.

items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [52]:
# code
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [53]:
np.flip(a) # Flip on 1D array reverses it.

array([13, 87, 72, 98, 13, 83, 87, 30, 47, 46, 51, 66, 42, 65, 89])

In [54]:
b

array([[52, 74, 95, 75],
       [48, 44, 96, 23],
       [ 8, 96, 32, 98],
       [63, 14,  2, 78],
       [49, 58, 61,  5],
       [74, 38, 61, 43]])

In [55]:
np.flip(b) # Flips matrix on both axis

array([[43, 61, 38, 74],
       [ 5, 61, 58, 49],
       [78,  2, 14, 63],
       [98, 32, 96,  8],
       [23, 96, 44, 48],
       [75, 95, 74, 52]])

In [56]:
np.flip(b,axis=1) # Flips columns

array([[75, 95, 74, 52],
       [23, 96, 44, 48],
       [98, 32, 96,  8],
       [78,  2, 14, 63],
       [ 5, 61, 58, 49],
       [43, 61, 38, 74]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [57]:
# code
a

array([89, 65, 42, 66, 51, 46, 47, 30, 87, 83, 13, 98, 72, 87, 13])

In [58]:
np.put(a,[0,1],[110,530])
# Substitutes 110 and 530 at index 0,1


### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [59]:
# code
a

array([110, 530,  42,  66,  51,  46,  47,  30,  87,  83,  13,  98,  72,
        87,  13])

In [60]:
np.delete(a,[0,2,4])

array([530,  66,  46,  47,  30,  87,  83,  13,  98,  72,  87,  13])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(n,m)

array([6, 7])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [65]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [66]:
# code
a

array([110, 530,  42,  66,  51,  46,  47,  30,  87,  83,  13,  98,  72,
        87,  13])

In [67]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 42, 66, 51, 46, 47, 30, 75, 75, 25, 75, 72, 75, 25])

### np.swapaxes

- Swaps axes with one other.
- Example- swapping values in row with values in a column
- More modifyable version of transpose

In [78]:
q = np.random.randint(10,100, size=12).reshape(3,4)
print(q)
np.swapaxes(q,0,1)

[[54 14 19 87]
 [26 17 97 31]
 [36 44 69 73]]


array([[54, 26, 36],
       [14, 17, 44],
       [19, 97, 69],
       [87, 31, 73]])

### np.squeeze

- It removes the dimenions where the size is 1.
- Or you can specify certain dimension to remove (only if it's 1, else it will give error)

In [88]:
p = np.random.randint(10,100, size = 8).reshape(1,1,2,1,2,2,1)
print(p)
print(p.shape)

print()

print(np.squeeze(p))
print(np.squeeze(p).shape)

print()

print(np.squeeze(p, axis=3))
print(np.squeeze(p, axis=3).shape)

[[[[[[[99]
      [19]]

     [[72]
      [14]]]]



   [[[[18]
      [76]]

     [[66]
      [64]]]]]]]
(1, 1, 2, 1, 2, 2, 1)

[[[99 19]
  [72 14]]

 [[18 76]
  [66 64]]]
(2, 2, 2)

[[[[[[99]
     [19]]

    [[72]
     [14]]]


   [[[18]
     [76]]

    [[66]
     [64]]]]]]
(1, 1, 2, 2, 2, 1)


### np.count_nonzero

Just as its name sounds.

### np.tile

Construct an array by repeating A the number of times given by reps. <br>
If reps has length d, the result will have dimension of max(d, A.ndim).


### np.allclose and equals

np.allclose() checks for equality between two arrays with some tolerance.<br>
np.equals() checks for equality without tolerance.

## Useful links

https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580